Repository jisung-in/frontend, pull requests merged in 2024-06, with the labels that each got.

#80 마이페이지 카드 컴포넌트 적용 및 헤더 폰트 적용
  src/app/components/Card/EvaluationCard/MyEvaluationCard.tsx
  src/app/components/Layout/Header/Header.tsx
  src/app/font.ts
  src/app/layout.tsx
  src/app/search/[word]/_component/MainContent.tsx
  src/app/search/[word]/_component/RelativeRoomCards.tsx
  src/app/summary/_component/Preface.tsx
  src/app/summary/layout.tsx
  src/app/summary/review/page.tsx
  src/app/summary/state/page.tsx
  src/app/summary/talkroom/_component/MyTalkRoom.tsx
  src/assets/font/Kalufo/Kalufonia-Regular.otf
  src/assets/img/summary-book.svg
  src/hook/reactQuery/my/useGetMyDetail.ts
  src/hook/reactQuery/my/useGetMyState.ts
  src/hook/reactQuery/talkRoom/useGetRoomLike.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🖼️ Asset

#81 마이 페이지 페이지네이션 적용
  src/app/components/Card/EvaluationCard/MyEvaluationCard.tsx
  src/app/summary/page.tsx
  src/app/summary/review/_component/ReviewContent.tsx
  src/app/summary/review/page.tsx
  src/app/summary/star/_component/MyStarContent.tsx
  src/app/summary/star/page.tsx
  src/app/summary/state/_component/MyStateContent.tsx
  src/app/summary/state/page.tsx
  src/app/summary/talkroom/_component/MyTalkRoom.tsx
  src/app/summary/talkroom/_component/Tab.tsx
  src/app/summary/talkroom/_component/TabProvider.tsx
  src/app/summary/talkroom/page.tsx
  src/constants/tabIndex.ts
  src/hook/reactQuery/my/useGetMyReview.ts
  src/hook/reactQuery/my/useGetMyStars.ts
  src/hook/reactQuery/my/useGetMyState.ts
  src/hook/reactQuery/my/useGetMyTalkRooms.ts
  src/hook/useGetPageParams.ts
  src/middleware.ts
Labels: 🐞 BugFix, 🔨 Refactor

#82 토크룸 생성시 이미지 첨부 기능 및 리다이렉트 추가
  src/app/components/molecules/ConditionButtons/ConditionButtons.tsx
  src/app/components/molecules/SearchedList/SearchedList.tsx
  src/app/detail/talkroom/new/page.tsx
  src/app/search/[word]/_component/RelativeRoomCards.tsx
  src/app/talkroom/_component/talkroomSearch.tsx
  src/constants/buttonIndex.ts
  src/hook/reactQuery/book/useGetBookInformation.ts
Labels: 🐞 BugFix, 🔨 Refactor

#83 토크방 이미지가 화면을 덮게 나오는 현상 수정
  src/app/talkroom/_component/talkroomDetailMain.tsx
Labels: 🐞 BugFix

#84 api 변경 및 추가로 해당 api와 관련된 부분의 수정 작업 및 추가 작업
  src/app/book/[isbn]/page.tsx
  src/app/book/_component/BookStatus.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/hook/reactQuery/book/useCreateBookState.ts
  src/hook/reactQuery/book/useDeleteBookState.ts
  src/hook/reactQuery/book/useGetBookState.ts
  src/hook/reactQuery/book/useGetReviewCount.ts
  src/hook/reactQuery/book/usePatchBookState.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
Labels: ✨ Feature, 🔨 Refactor

#85 읽은 책 상태 관련 typescript수정, 잘못된 조건식 수정
  src/app/talkroom/detail/[id]/page.tsx
  src/hook/reactQuery/book/useGetBookState.ts
Labels: 🔨 Refactor

#86 책 상세보기 페이지로 접근할 때, 비 로그인시 에러가 발생하는 현상 수정
  src/app/book/_component/BookStatus.tsx
Labels: 🔨 Refactor

#89 메인 페이지 배너 컴포넌트 제작 및 토크룸 생성 전페이지 제작
  src/app/components/Button/Button.tsx
  src/app/components/MainSelectionCard/MainSelectionCard.tsx
  src/app/detail/talkroom/_component/TalkRoomSelection.tsx
  src/app/detail/talkroom/new/page.tsx
  src/app/detail/talkroom/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/img/evalutaion.svg
  src/assets/img/question.svg
  src/assets/img/record.svg
  src/assets/img/smaller_evaluation.svg
  src/assets/img/smaller_question.svg
  src/assets/img/smaller_record.svg
  src/styles/theme/colors.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset
