Repository jisung-in/frontend, pull requests merged in 2024-03, with the labels that each got.

#6 1 add components
  src/app/components/Button/Button.stories.tsx
  src/app/components/Button/Button.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/Card.types.ts
  src/app/components/Footer/Footer.tsx
  src/app/components/Header/Header.tsx
Labels: ✨ Feature

#15 1 add components
  src/app/components/Book/Book.tsx
  src/app/components/Book/Book.types.ts
  src/app/components/Card/Card.tsx
  src/app/components/Card/Card.types.ts
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/CardHeader/CardHeader.types.ts
  src/app/components/Theme/Theme.tsx
  src/app/components/Theme/Theme.types.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/img/like.svg
  src/styles/theme/border.ts
  src/styles/theme/index.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design, 🖼️ Asset

#17 feat: Swiper component 임시 추가
  src/app/components/Swiper/SliderButton.tsx
  src/app/components/Swiper/Swiper.tsx
Labels: ✨ Feature

#18 1 add components
  src/app/components/Book/Book.tsx
  src/app/components/Book/Book.types.ts
  src/app/components/Card/Card.tsx
  src/app/components/Card/Card.types.ts
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/CardHeader/CardHeader.types.ts
  src/app/page.tsx
  src/assets/img/star.svg
Labels: ✨ Feature, 🖼️ Asset

#19 탭 컴포넌트 생성 && 마이 페이지 레이아웃 기초
  package.json
  src/app/components/Button/Button.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/MyInfoCard/MyBookCard.tsx
  src/app/components/Card/ReviewCard/ReviewCard.tsx
  src/app/components/Card/RoomCard/RoomCard.tsx
  src/app/components/Layout/Header/Header.tsx
  src/app/my/_component/SummaryCard.tsx
  src/app/my/edit/layout.tsx
  src/app/my/layout.tsx
  src/app/my/page.tsx
  src/app/page.tsx
  src/app/summary/_component/BackButton.tsx
  src/app/summary/_component/Preface.tsx
  src/app/summary/_component/Tabs.tsx
  src/app/summary/layout.tsx
  src/app/summary/page.tsx
  src/app/summary/review/page.tsx
  src/app/summary/star/page.tsx
  src/app/summary/state/page.tsx
  src/app/summary/talkroom/page.tsx
  src/assets/img/arrow.svg
  src/assets/img/back-arrow.svg
  src/constants/tabIndex.ts
  src/styles/theme/colors.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#20 1 add components
  src/app/components/Card/Card.tsx
  src/app/components/CardFooter/CardFooter.tsx
  src/app/components/CardFooter/CartFooter.types.ts
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/TalkComment/TalkComment.tsx
  src/app/components/TalkComment/TalkComment.types.ts
  src/app/page.tsx
  src/assets/img/like.svg
  src/assets/img/numbering.svg
  src/assets/img/star.svg
Labels: ✨ Feature, 🖼️ Asset

#21 1 add components
  src/app/components/CardFooter/CardFooter.tsx
  src/app/components/CommentHeartButton/CommentHeartButton.tsx
  src/app/components/CommentHeartButton/CommentHeartButton.types.ts
  src/app/components/HeartButton/HeartButton.tsx
  src/app/components/HeartButton/HeartButton.types.ts
  src/app/components/LikeButton/LikeButton.tsx
  src/app/components/LikeButton/LikeButton.types.ts
  src/app/page.tsx
  src/assets/img/comment-like.svg
  src/assets/img/like.svg
  src/assets/img/not-like.svg
Labels: ✨ Feature

#23 16 cards required on the main page
  src/app/components/Book/Book.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/components/Theme/Theme.tsx
  src/app/components/Theme/Theme.types.ts
  src/app/globals.css
  src/app/page.tsx
  src/assets/img/best-seller.svg
  src/assets/img/many-talk-room-book.svg
  src/assets/img/popular-talk-room.svg
  src/assets/img/recent-make-talk-room.svg
  src/assets/img/recent-opinion-talk-room.svg
  src/assets/img/register-recent-book.svg
  src/assets/img/swiper-next-button.png
  src/assets/img/swiper-prev-button.png
Labels: ✨ Feature, 🎨 Design
