Repository jisung-in/frontend, pull requests merged in 2024-04, with the labels that each got.

#25 토크해요 페이지 완성
  src/app/components/Book/Book.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/ReviewCard/ReviewCard.tsx
  src/app/components/Card/RoomCard/RoomCard.tsx
  src/app/components/CardFooter/CardFooter.tsx
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/LikeButton/LikeButton.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/components/TalkComment/TalkComment.tsx
  src/app/components/Theme/Theme.tsx
  src/app/letsTalk/[result]/page.tsx
  src/app/letsTalk/_component/StatusBurtton.tsx
  src/app/letsTalk/layout.tsx
  src/app/letsTalk/page.tsx
  src/app/page.tsx
  src/assets/img/make-talk-room.svg
  src/assets/img/next-arrow.svg
  src/assets/img/prev-arrow.svg
Labels: ✨ Feature

#26 feat: 쓰지 않는 useSearchParams 제거 및 배포 오류 테스트중
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/StatusBurtton.tsx
  src/app/talkroom/layout.tsx
  src/app/talkroom/page.tsx
Labels: 🌏 Deploy, ✨ Feature

#29 28 edit card component
  src/app/components/Book/Book.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/Card.types.ts
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/PopularTalkRoomCard/PopularTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard/TalkRoomCard.tsx
  src/app/components/Card/ReviewCard/ReviewCard.tsx
  src/app/components/Card/RoomCard/RoomCard.tsx
  src/app/components/Card/TalkRoomCard/TalkRoomCard.tsx
  src/app/components/CardFooter/CardFooter.tsx
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/HeartButton/HeartButton.tsx
  src/app/components/HeartButton/HeartButton.types.ts
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/components/TalkCommentHeader/TalkCommentHeader.tsx
  src/app/components/TalkCommentHeader/TalkCommentHeader.types.ts
  src/app/globals.css
  src/app/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/layout.tsx
  src/app/talkroom/page.tsx
  src/assets/img/book-title.svg
  src/assets/img/not-like-white.svg
  src/assets/img/not-like.svg
  src/assets/img/talkroom-title.svg
  src/assets/img/theme-title.svg
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset

#35 Ui 변경 및 필터 추가
  src/app/components/Card/MainPageCard/PopularTalkRoomCard/PopularTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard/TalkRoomCard.tsx
  src/app/components/Card/TalkRoomCard/TalkRoomCard.tsx
  src/app/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/BestSpeechBubble.tsx
  src/app/talkroom/_component/SpeechBubble/MySpeechBubble.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/page.tsx
  src/assets/img/like.svg
  yarn.lock
Labels: ✨ Feature, 🎨 Design

#36 유저들의 평가 페이지 ui 제작
  src/app/components/Book/Book.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard/TalkRoomCard.tsx
  src/app/components/CardHeader/CardHeader.tsx
  src/app/components/MainThemeTitle/MainThemeTitle.tsx
  src/app/evaluation/layer.tsx
  src/app/evaluation/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/page.tsx
  src/app/talkroom/page.tsx
  src/assets/img/user-evaluation.svg
Labels: ✨ Feature, 🎨 Design

#38 MSW 적용
  next.config.js
  package.json
  public/mockServiceWorker.js
  src/app/api/requestApi.ts
  src/app/components/Card/MyInfoCard/MyBookCard.tsx
  src/app/components/Provider/MSWProvider/MSWProvider.tsx
  src/app/layout.tsx
  src/app/search/[word]/page.tsx
  src/app/summary/star/page.tsx
  src/app/summary/state/page.tsx
  src/hook/reactQuery/my/useMyStarRate.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/http.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#39 27 add book detail page
  src/app/book/_component/BookInformation.tsx
  src/app/book/detail/layout.tsx
  src/app/book/detail/page.tsx
  src/app/book/layout.tsx
  src/app/book/page.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/EvaluationCard/EvaluationMiniCard.tsx
  src/assets/img/big-star.svg
  src/assets/img/empty-star.svg
  src/assets/img/half-star.svg
  src/assets/img/pasue-on.svg
  src/assets/img/pause-off.svg
  src/assets/img/read-off.svg
  src/assets/img/read-on.svg
  src/assets/img/read-stop-off.svg
  src/assets/img/read-stop-on.svg
  src/assets/img/reading-off.svg
  src/assets/img/reading-on.svg
  src/assets/img/want-to-read-off.svg
  src/assets/img/want-to-read-on.svg
Labels: ✨ Feature, 🎨 Design, 🖼️ Asset

#42 40 edit card UI - 카드 ui 변경
  public/data.json
  public/dataType.ts
  src/app/book/_component/BookInformation.tsx
  src/app/components/Book/Book.tsx
  src/app/components/Card/BestSellerCard.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/EvaluationCard/EvaluationMiniCard.tsx
  src/app/components/Card/MainCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/RecommendCard.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/components/Theme/Theme.tsx
  src/app/globals.css
  src/app/page.tsx
  src/assets/img/recommend-talk-room.svg
  src/assets/img/theme-title.svg
  src/assets/img/write-opinion.svg
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#45 43 add infinity scroll and edit star rate function
  src/app/book/_component/BookInformation.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/MainCard.tsx
  src/app/components/Card/RecommendCard.tsx
  src/app/evaluation/page.tsx
  src/assets/img/book-title-evaluation.svg
  src/assets/img/pause-off.svg
  src/assets/img/read-stop-off.svg
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset

#47 MSW적용 및 css 수정
  public/data.json
  public/dataType.ts
  src/app/book/detail/page.tsx
  src/app/components/Card/BestSellerCard.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/EvaluationCard/EvaluationMiniCard.tsx
  src/app/components/Card/MainCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/RecommendCard.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/evaluation/page.tsx
  src/app/page.tsx
  src/app/talkroom/detail/page.tsx
  src/hook/reactQuery/evaluation/useBookEvaluationUser.ts
  src/hook/reactQuery/evaluation/useEvaluationUser.ts
  src/hook/reactQuery/main/useBookRank.ts
  src/hook/reactQuery/main/useTalkRoomMany.ts
  src/hook/reactQuery/main/useTalkRoomPopular.ts
  src/hook/reactQuery/main/useTalkRoomRecommend.ts
  src/mocks/handlers.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#48 DropDown 공통 컴포넌트화
  src/app/components/DropDown/DropDown.tsx
  src/app/evaluation/page.tsx
  src/app/summary/page.tsx
  src/app/summary/star/page.tsx
Labels: ✨ Feature

#50 페이지 UI 수정
  src/app/book/detail/page.tsx
  src/app/components/Card/RecommendCard.tsx
  src/app/components/Card/RelatedTalkRoomCard.tsx
  src/app/components/Card/TalkRoomCard.tsx
  src/app/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/StatusBurtton.tsx
  src/app/talkroom/layout.tsx
  src/app/talkroom/page.tsx
  src/assets/img/book-title-relate.svg
  src/assets/img/theme-title-middle.svg
  src/hook/reactQuery/main/useGetBookRank.ts
  src/hook/reactQuery/main/useGetTalkRoomMany.ts
  src/hook/reactQuery/main/useGetTalkRoomPopular.ts
  src/hook/reactQuery/main/useGetTalkRoomRecommend.ts
  src/mocks/handlers.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset
