Repository jisung-in/frontend, pull requests merged in 2024-07, with the labels that each got.

#91 svg 컴포넌트 내에 current 값으로 인한 오류 해결
  src/assets/img/evalutaion.svg
  src/assets/img/question.svg
  src/assets/img/record.svg
Labels: 🐞 BugFix

#90 메인페이지 피보팅 작업
  src/app/components/Button/Button.tsx
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/BestSellerTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/MainSelectionCard/MainSelectionCard.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Swiper/BestSellerSwiper.tsx
  src/app/components/Swiper/RankSwiper.tsx
  src/app/components/Theme/Theme.tsx
  src/app/detail/talkroom/_component/TalkRoomSelection.tsx
  src/app/font.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/talkroom/related/[isbn]/page.tsx
  src/assets/font/Jalnan2/Jalnan2.otf
  src/assets/img/create-talk-room.svg
  src/assets/img/not-like.svg
  src/assets/img/rank1.svg
  src/assets/img/rank2.svg
  src/assets/img/rank3.svg
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#93 스켈레톤 UI 적용
  package.json
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/BestSellerTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/MainSelectionCard/MainSelectionCard.tsx
  src/app/components/SkeletonUI/DeferredComponent .tsx
  src/app/components/SkeletonUI/SkeletonLoadingSwiper.tsx
  src/app/components/SkeletonUI/SkeletonTalkRoomCard.tsx
  src/app/components/Swiper/BestSellerSwiper.tsx
  src/app/components/Swiper/RankSwiper.tsx
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#95 메인 페이지 무한 스크롤 적용 및 hook 수정
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/RelativeRoomCards.tsx
  src/app/search/[word]/_component/RoomCards.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/page.tsx
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: ✨ Feature, 🔨 Refactor

#97 토크방 - 기록 pivoting
  src/app/page.tsx
  src/app/talkroom/_component/talkroomSearch.tsx
  src/app/talkroom/evaluation/page.tsx
  src/app/talkroom/layout.tsx
  src/app/talkroom/page.tsx
  src/app/talkroom/question/[result]/layout.tsx
  src/app/talkroom/question/[result]/page.tsx
  src/app/talkroom/question/page.tsx
  src/app/talkroom/record/[result]/layout.tsx
  src/app/talkroom/record/[result]/page.tsx
  src/app/talkroom/record/page.tsx
  src/app/talkroom/related/[isbn]/layout.tsx
  src/app/talkroom/related/[isbn]/page.tsx
  src/hook/reactQuery/talkRoom/useGetRooms.ts
  src/util/searchTalkRoomDate.tsx
  src/util/searchTalkRoomStatus.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#99 무한스크롤 관련 작업
  src/app/book/[isbn]/page.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/SkeletonUI/DeferredComponent .tsx
  src/app/components/Swiper/BestSellerSwiper.tsx
  src/app/page.tsx
  src/app/talkroom/_component/talkroomSearch.tsx
  src/app/talkroom/record/[result]/layout.tsx
  src/app/talkroom/record/[result]/page.tsx
  src/app/talkroom/record/page.tsx
  src/hook/reactQuery/talkRoom/useGetRooms.ts
  src/util/useObserver.tsx
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design
