Repository jisung-in/frontend, pull requests merged in 2024-05, with the labels that each got.

#56 메인페이지, 토크방, 책 상세보기 페이지 api연결 작업
  next.config.js
  src/app/book/[isbn]/layout.tsx
  src/app/book/[isbn]/page.tsx
  src/app/book/_component/BookInformation.tsx
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/RecommendCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/IconButton/IconButton.tsx
  src/app/components/IconButton/IconButton.types.ts
  src/app/components/Swiper/SliderButton.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/BookCards.tsx
  src/app/search/[word]/_component/RoomCards.tsx
  src/app/summary/talkroom/page.tsx
  src/app/talkroom/[status]/[result]/layout.tsx
  src/app/talkroom/[status]/[result]/page.tsx
  src/app/talkroom/[status]/layout.tsx
  src/app/talkroom/[status]/page.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/StatusBurtton.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/[id]/layout.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/app/test/page.tsx
  src/hook/reactQuery/book/useGetBookDetail.ts
  src/hook/reactQuery/main/useGetBookRank.ts
  src/hook/reactQuery/main/useGetTalkRoomBookOrder.ts
  src/hook/reactQuery/main/useGetTalkRoomMany.ts
  src/hook/reactQuery/main/useGetTalkRoomPopular.ts
  src/hook/reactQuery/main/useGetTalkRoomRecommend.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: 🐞 BugFix, 🌏 Deploy, ✨ Feature, 🔨 Refactor, 🎨 Design, 🗑️ Remove, 🖼️ Asset

#57 52 apply api and modify UI
  src/app/book/_component/BookInformation.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/BookCards.tsx
  src/app/talkroom/[result]/layout.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/[status]/[result]/layout.tsx
  src/app/talkroom/[status]/[result]/page.tsx
  src/app/talkroom/[status]/layout.tsx
  src/app/talkroom/[status]/page.tsx
  src/app/talkroom/_component/StatusBurtton.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/layout.tsx
  src/app/talkroom/page.tsx
Labels: 🌏 Deploy, ✨ Feature

#59 reactQuery관련 typescript 수정 및 반영
  src/app/book/[isbn]/page.tsx
  src/app/book/_component/BookInformation.tsx
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/page.tsx
  src/app/summary/talkroom/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/comment/page.tsx
  src/app/talkroom/page.tsx
  src/app/test/page.tsx
  src/hook/reactQuery/book/useCreateBookState.ts
  src/hook/reactQuery/book/useGetBookInformation.ts
  src/hook/reactQuery/book/useGetBookRank.ts
  src/hook/reactQuery/book/useGetBookState.ts
  src/hook/reactQuery/main/useGetTalkRoomPopular.ts
  src/hook/reactQuery/talkRoom/useCreateRoom.ts
  src/hook/reactQuery/talkRoom/useGetComments.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
  src/hook/reactQuery/talkRoom/useGetRoomBookOrder.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: ✨ Feature, 🔨 Refactor

#61 연관된 토크방, 토크해요 검색 기능 반영, UI수정
  src/app/book/[isbn]/page.tsx
  src/app/book/_component/BookInformation.tsx
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Swiper/Swiper.tsx
  src/app/page.tsx
  src/app/summary/talkroom/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/talkroomSearchFunction.tsx
  src/app/talkroom/page.tsx
  src/assets/img/no-image.png
  src/hook/reactQuery/book/useGetBookRank.ts
  src/hook/reactQuery/book/useGetBookRelatedTalkRoom.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset

#62 최근 검색어 기능 및 모달 컴포넌트 생성
  src/app/components/Layout/Footer/Footer.tsx
  src/app/components/Layout/Header/Header.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/molecules/SearchedList/SearchedList.tsx
  src/app/summary/_component/BackButton.tsx
  src/app/summary/talkroom/_component/Tab.tsx
  src/hook/useRecentSearches.ts
Labels: ✨ Feature, 🔨 Refactor

#66 Ui수정, 도서 상태 api 연동, 토크방 api수정, 메인페이지 로직 수정
  src/app/book/_component/BookStatus.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/page.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/hook/reactQuery/book/useDeleteBookState.ts
  src/hook/reactQuery/book/useGetBookRank.ts
  src/hook/reactQuery/book/usePatchBookState.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#67 토크방 좋아요 기능, 의견 추가 및 기능 추가
  src/app/book/[isbn]/page.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/RoomCards.tsx
  src/app/summary/talkroom/_component/MyTalkRoom.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/app/talkroom/page.tsx
  src/app/talkroom/related/[isbn]/page.tsx
  src/hook/reactQuery/talkRoom/useCreateCommentLike.ts
  src/hook/reactQuery/talkRoom/useCreateRoomLike.ts
  src/hook/reactQuery/talkRoom/useDeleteCommentLike.ts
  src/hook/reactQuery/talkRoom/useDeleteRoomLike.ts
  src/hook/reactQuery/talkRoom/useGetComments.ts
  src/util/timeLapse.tsx
Labels: ✨ Feature, 🔨 Refactor

#68 배포 환경에서 카카오 API 호출 안되는 현상 Fix
  next.config.js
  src/app/api/requestApi.ts
  src/app/page.tsx
  src/app/search/[word]/_component/BookCards.tsx
  src/app/search/[word]/_component/PopularBook.tsx
  src/app/summary/star/page.tsx
  src/app/talkroom/comment/page.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/hook/reactQuery/book/useGetBookRank.ts
  src/hook/reactQuery/my/useGetMyStarRate.ts
  src/hook/reactQuery/my/useGetMyTalkRooms.ts
  src/hook/reactQuery/talkRoom/useCreateComment.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
  src/hook/useImageUpload.ts
  src/hook/useLocalStorage.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🖼️ Asset

#69 메인 페이지 반응형 적용
  src/app/components/Book/Book.tsx
  src/app/components/Card/MainPageCard/BestSellerCard.tsx
  src/app/components/Card/MainPageCard/ManyTalkRoomBookCard.tsx
  src/app/components/Card/MainPageCard/RecommendCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/HaveNotData/HaveNotData.tsx
  src/app/components/MainThemeTitle/MainThemeTitle.tsx
  src/app/components/ResizeImage/ResizeImage.tsx
  src/app/components/Swiper/RankSwiper.tsx
  src/app/components/Swiper/TalkRoomCardSwiper.tsx
  src/app/components/Theme/Theme.tsx
  src/app/page.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/page.tsx
  src/assets/img/best-seller.svg
  src/assets/img/many-talk-room-book.svg
  src/assets/img/popular-talk-room.svg
  src/assets/img/recent-make-talk-room.svg
  src/hook/reactQuery/book/useGetBookRank.ts
  src/hook/reactQuery/talkRoom/useGetComments.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#72 api변경 사항 적용, 좋아요 관련 hook생성 및 적용, 개선 및 에러 수정
  public/mockServiceWorker.js
  src/app/book/[isbn]/page.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/EvaluationCard/MiniEvaluationCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/evaluation/[isbn]/page.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/RoomCards.tsx
  src/app/summary/talkroom/_component/MyTalkRoom.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/app/talkroom/page.tsx
  src/app/talkroom/related/[isbn]/page.tsx
  src/hook/reactQuery/book/useCreateReviewLike.ts
  src/hook/reactQuery/book/useDeleteReviewLike.ts
  src/hook/reactQuery/book/useGetBookRelatedTalkRoom.ts
  src/hook/reactQuery/book/useGetReviewLike.ts
  src/hook/reactQuery/talkRoom/useGetCommentLike.ts
  src/hook/reactQuery/talkRoom/useGetComments.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
  src/hook/reactQuery/talkRoom/useGetRoomLike.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#73 데이터 형식 변경으로 인한 typescript수정
  src/app/book/[isbn]/page.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/page.tsx
  src/hook/reactQuery/book/useCreateReviewLike.ts
  src/hook/reactQuery/book/useDeleteReviewLike.ts
  src/hook/reactQuery/book/useGetBookRelatedTalkRoom.ts
Labels: 🔨 Refactor

#74 에러 수정, css변경, 토크방 생성하기 링크 연결 작업
  src/app/book/_component/BookStarRating.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/talkroomSearch.tsx
  src/app/talkroom/page.tsx
  src/assets/img/bubble-arrow.svg
Labels: 🔨 Refactor, 🎨 Design, 🖼️ Asset

#76 데이터 추가로 인한 typescript 수정 작업, 토크방, 의견, 평가에 대한 삭제 기능 추가
  next.config.js
  src/app/book/[isbn]/page.tsx
  src/app/book/_component/BookInformation.tsx
  src/app/book/_component/BookStarRating.tsx
  src/app/book/_component/BookStatus.tsx
  src/app/book/_component/registerEvaluation.tsx
  src/app/book/page.tsx
  src/app/components/Card/EvaluationCard/EvaluationCard.tsx
  src/app/components/Card/EvaluationCard/MiniEvaluationCard.tsx
  src/app/components/Card/MainPageCard/RelatedTalkRoomCard.tsx
  src/app/components/Card/MainPageCard/TalkRoomCard.tsx
  src/app/components/DeleteButton/DeleteButton.tsx
  src/app/components/LikeButton/LikeButton.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/ModifyButton/ModifyButton.tsx
  src/app/components/Swiper/TalkRoomCardSwiper.tsx
  src/app/evaluation/[isbn]/page.tsx
  src/app/page.tsx
  src/app/search/[word]/_component/RoomCards.tsx
  src/app/summary/talkroom/_component/MyTalkRoom.tsx
  src/app/talkroom/[result]/page.tsx
  src/app/talkroom/_component/SpeechBubble/MySpeechBubble.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/_component/talkroomDetailMain.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/app/talkroom/page.tsx
  src/app/talkroom/related/[isbn]/page.tsx
  src/assets/img/my-bubble-arrow.svg
  src/hook/reactQuery/book/useGetBookRelatedTalkRoom.ts
  src/hook/reactQuery/book/useGetReview.ts
  src/hook/reactQuery/my/useGetMyDetail.ts
  src/hook/reactQuery/talkRoom/useDeleteComment.ts
  src/hook/reactQuery/talkRoom/useDeleteRoom.ts
  src/hook/reactQuery/talkRoom/useGetComments.ts
  src/hook/reactQuery/talkRoom/useGetOneRoom.ts
  src/hook/reactQuery/talkRoom/useGetRooms.ts
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design, 🖼️ Asset

#79 의견 말풍선 로직 및 css 수정, 무한스크롤 추가, 에러 수정
  src/app/book/[isbn]/page.tsx
  src/app/evaluation/[isbn]/page.tsx
  src/app/talkroom/_component/SpeechBubble/MySpeechBubble.tsx
  src/app/talkroom/_component/SpeechBubble/SpeechBubble.tsx
  src/app/talkroom/detail/[id]/page.tsx
  src/hook/reactQuery/book/useGetReview.ts
Labels: ✨ Feature, 🔨 Refactor
